version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3001:80" 
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000" 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
